server:
  port: 8080
spring:
  application:
    name: "payment_system"
  datasource:
    url: jdbc:h2:./db/payment_system;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yml
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    org:
      springframework:
        security: debug

springdoc:
  api-docs:
    path: /v3/api-docs
